# Generated by Django 5.2.3 on 2025-07-17 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TodoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('marked_as_done_at', models.DateTimeField(blank=True, null=True)),
                ('is_done', models.BooleanField(default=False)),
            ],
        ),
    ]
